                      // Updated list: Pickles, Chutneys & Pastes
                      const alreadyUpdated = [
                        "PATTU-URID WHOLE WHITE-4KG",
                        "GAJANAND-URID GOTA-1KG",
                        "DRYGRAB-MOTH BEANS-100GM",
                        "SAURBHI-MUNG SPLIT GREEN WITH SKIN-1KG",
                        "SAURBHI-MOONG BEAN BERKEN-1 KG",
                        "SAURBHI-CHICK PEAS KABULI-1 KG",
                        "VIYA-BLACK URID/URAD SPLIT-1 KG",
                        "ORGANIC TATTVA-ORGANIC AMARANTH-500GM",
                        "ORGANIC TATTVA-ORGANIC FOXTAIL MILLET-500GM",
                        "BANSI-ROASTED SALTED KABULI CHANA-400GM",
                        "THE SPICE FACTORY-MOTH BEANS-1KG",
                        "ROYAL GOLD-ROASTED DALIA-1KG",
                        "KHUSHBOO-CHANA DALIYA-400GM",
                        "BANSI-TANGY CHANA-200GM",
                        "HECHAM-LIMA BEANS-1KG",
                        "BANSI-ROSTED GULABI CHANA-400GM",
                        "4 CORNER-MIXED SOUP (QWATTI)-1 KG",
                        "VIYA-CHICK PEAS KABULI-1 KG",
                        "VIYA-YELLOW SPLIT PEA-1 KG",
                        "VIYA-TYSON CHICK PEAS/KALA CHANNA-1 KG",
                        "MAHARAJA CHOICE-POONA BEANS-1KG",
                        "MAHARAJA CHOICE-RED LENTILS-1KG",
                        "BALACK EYE BEANS 1KG",
                        "JK-URID GOTA-1KG",
                        "JK-URID WHOLE-BLACK MUNG-1KG",
                        "JK-CHANA DAL-1KG",
                        "JK- CHANNA DHALL 2KG",
                        "JK-CHICK PEA TYSON-1KG",
                        "J K -MASOOR DAL -1KG",
                        "PUNJABI-DAL-1KG",
                        "JK- MUNG BEANS- 1KG",
                        "INDYA-TOOR DAL-1KG",
                        "UTTAM-ROASTED CHANA-500 GM",
                        "UTTAM-CHANA WTH SKIN-500M",
                        "PATTU-MOONG BEAN BERKEN-2 KG",
                        "TSF-DRY HARAD-100GM",
                        "DELHI 6-ROASTED CHANA-400GM",
                        "TFS WHOLE BAJRA-500GM",
                        "DELHI 6-ROASTED CHANA-800GM 2",
                        "PATTU-RED KIDNEY BEANS LIGHT/RAJMAH-5 KG",
                        "SAURBHI-BLACK TURTLE BEANS-1 KG",
                        "PATTU-BLUE PEAS-1KG",
                        "PATTU-URID DHALL WHITE-1 KG",
                        "PATTU-ADZUKI BEAN-1KG",
                        "INDYA-MOONG SPLIT-1KG",
                        "SAURBHI-TOOR DAL-1KG",
                        "KATOOMBA-BLACK LENTIL-1 KG",
                        "KATOOMBA-CHICK PEAS ORD RIVER-1 KG",
                        "KATOOMBA-BORLOTTI BEANS-1 KG",
                        "KATOOMBA-RED KIDNEY BEANS LIGHT/RAJMAH-1 KG",
                        "KATOOMBA-RED SPLIT LENTIL/MASOOR DAL-1 KG",
                        "SAURBHI-ROASTED GRAM-400 GM",
                        "KATOOMBA-MOONG DAL-1 KG",
                        "KATOOMBA-URID/URAD SPLIT WITH SKIN-1 KG",
                        "PATTU-GREEN LENTIL(AUSTRALIAN)-1 KG",
                        "PATTU-TOOR DHALL-1KG",
                        "HECHAM-FABA BEANS-1KG",
                        "PATTU-RED SPLIT LENTILS-5KG",
                        "IDIYA ROSTED GRAM-1KG",
                        "DEEP-TOOR DAL-907GM",
                        "SAURBHI- MOONG BARKEN-2KG",
                        "INDYA-CHANA DAAL-1KG",
                        "DEEP-MASSOR DAAL-1KG",
                        "DELHI-6-JAMMU RAJMA-1KG",
                        "INDIYA TOOR DAAL -5KG",
                        "SAURABHI-WHOLE WHEAT-1KG",
                        "DELHI 6 MOTH BEANS 1KG",
                        "PATTU-RED LENTIL WHOLE/MASOOR GOTA-1 KG",
                        "PATTU-RED SPLIT LENTIL/MASOOR DAL-1 KG",
                        "PATTU-GREEN SPLIT PEA-1 KG",
                        "PATTU-RED SPLIT LENTIL/MASOOR DAL-2KG",
                        "PATTU-YELLOW SPLIT PEAS-2KG",
                        "THE SPICE FACTORY-HORSE GRAM-1KG",
                        "MARATHI WSWAD-KADVE WAL",
                        "PATTU-CHANNA DAL-2KG",
                        "PATTU-CHICK PEAS KABULI 9MM-2KG",
                        "PARSRAM-MOONG MASOOR-1KG",
                        "PARSRAM-TOOR DAL-1KG",
                        "RED-KIDNEY-BEAN",
                        "PARSRAM-WHITE PEA-1KG",
                        "PARSRAM-JAMMU RAJMA-1KG",
                        "PARSRAM-HORSE GARAM-1KG",
                        "KATOOMBA-GREEN SPLIT PEA-1 KG",
                        "PATTU-URID WHOLE WHITE-1KG",
                        "UTTAM-ROASTED CHANA WITH SKIN-1 KG",
                        "PATTU-URID/URAD WHOLE BLACK-2KG",
                        "PATTU-URID/URAD WHOLE BLACK-2 KG",
                        "INDYA-MOONG DAL(YELLOW)-2 KG",
                        "INDYA-TOOR DAL-2 KG",
                        "FARM KING-TOOR DAL-5KG",
                        "KATOOMBA-RED KIDNEY BEANS DARK/RAJMAH-1 KG",
                        "KATOOMBA-CHANNA DAL-1 KG",
                        "KATOOMBA-CHICK PEAS KABULI-1 KG",
                        "PATTU-TYSON CHICK PEAS/KALA CHANNA-1 KG",
                        "PATTU MUNG SPLITS WITH SKIN 1kg",
                        "PATTU-YELLOW SPLIT PEA-1KG",
                        "PATTU-URID/URAD WHOLE BLACK-1 KG",
                        "PATTU-CHICK PEAS KABULI-1 KG",
                        "PATTU-BLACK EYE BEANS-1KG",
                        "PATTU-POPCORN-1KG",
                        "PATTU-POP CORN-500GM",
                        "PATTU-RED KIDNEY BEANS DARK/RAJMAH-1 KG",
                        "PATTU-CHICK PEAS ORD RIVER-1 KG",
                        "PATTU-POTTU KADALAI SPLI GRAM-250 GM",
                        "PATTU-MUNG CELERA-1 KG",
                        "PATTU-OILY TOOR DHAL-2KG",
                        "PATTU-MUNG BEAN CELERA-2KG",
                        "PATTU-WHEAT-1 KG",
                        "PATTU-CHICK PEAS ORD RIVER-5 KG",
                        "PATTU-RED KIDNEY BEANS DARK/RAJMAH-2 KG",
                        "PATTU-TYSON CHICK PEAS/KALA CHANNA-2 KG",
                        "PATTU-ROSTED SPLIT GRAM- 1KG",
                        "HINDUSTAN-BLACK EYE BEANS-1KG",
                        "HINDUSTAN-BLUE PEAS-1KG",
                        "HINDUSTAN-BORGOL COARSE-1KG",
                        "HINDUSTAN-CHICK PEA (KABULI)-1KG",
                        "HINDUSTAN-CHICK PEA ORD RIVER-1KG",
                        "HINDUSTAN-CHICK PEA OLD RIVER-5KG",
                        "HINDUSTAN-BLACK CHICK PEA-1KG",
                        "HINDUSTAN-CORN WHITE-1KG",
                        "HINDUSTAN-GREEN LENTIL-1KG",
                        "HINDUSTAN-LABLAB BEANS-1 KG",
                        "HINDUSTAN-MUNG BURKEN-1KG",
                        "HINDUSTAN-MUNG (IND)-1KG",
                        "HINDUSTAN-MUNG GREEN SPLIT-1KG",
                        "HINDUSTAN-PUNA BEANS-1KG",
                        "HINDUSTAN-RED KIDNEY BEANS DARK-1KG",
                        "HINDUSTAN-RED KIDNEY BEANS RAJMA LIGHT-1KG",
                        "HINDUSTAN-SOYA BEANS-1KG",
                        "HINDUSTAN-TOOR DHALL-1KG",
                        "HINDUSTAN-URID DAL WHITE SPLIT-1KG",
                        "HINDUSTAN-URID WHITE GOTA-1KG",
                        "HINDUSTAN-URAD DAL- 5KG",
                        "HINDUSTAN-VATANA WHITE-1KG",
                        "HINDUSTAN-WHOLE WHEAT -1KG",
                        "HINDUSTAN-BLACKL LENTILS-1KG",
                        "PATTU-BLUE PEAS-2 KG",
                        "PATTU-CHICK PEAS ORD RIVER-2 KG",
                        "PATTU-BLACK EYE BEANS-2 KG",
                        "PATTU-MOONG DAL-2 KG",
                        "PATTU-MIXED BEANS-1 KG",
                        "PATTU-MOONG MASOOR MIX-1KG",
                        "PATTU-WHITE PEAS -1 KG",
                        "HECHAM-BARLEY-1KG",
                        "HECHAM-BLACK EYE BEANS 1K",
                        "VIYA-ADZUKI BEANS-1 KG",
                        "VIYA-BLUE PEAS-1 KG",
                        "4 CORNER-ROASTED RICE BEANS (MASYANG)-500 GM",
                        "4 CORNER-MIXED DAL-500 GM",
                        "INDYA-TOOR DAL-2 KG 2",
                        "VIYA-RED KIDNEY BEANS LIGHT/RAJMAH-1 KG",
                        "SAURBHI-CHICK PEAS ORD RIVER-1 KG",
                        "VIYA-BLACK URID/URAD DAL-1 KG",
                        "SAURBHI-MOTH BEAN-1 KG",
                        "SAURBHI-RED KIDNEY BEANS JAMMU/RAJMAH-1 KG",
                        "PATTU-CHICK PEAS KABULI-2 KG",
                        "SAURABHI-MOONG DHALL YELLOW-2KG",
                        "JK-MASOOR DAAL-4KG",
                        "JK-CHIK PEA-4KG",
                        "INDIYA-DALIYA SPLIT-200GM",
                        "DALIA 1KG",
                        "TSF-MIX DAAL-1KG",
                        "PATTU- BLACK UDID WHOLE-5KG",
                        "SAURABHI-MUNG BEARKEN-5KG",
                        "DEEP-URID GOTA-1KG",
                        "SAURABHI-URID DHALL WHITE-2KG",
                        "DEEP-MUNG DAAL-1KG",
                        "INDYA-MOONG MASOOR DAL-1KG",
                        "PATTU-MUNG DALL-5KG",
                        "SAURABHI-RED KIDNEY BEANS LIGHTS-2KG",
                        "JK-SORGHUM SEED RED-1KG",
                        "INDYA-WHEAT DALIA-1KG",
                        "PATTU-MUNG SPLIT(WITH SKIN)-2KG",
                        "KHUSHBOO-CHANA GOTA-400GM",
                        "KHUSHBOO-ROASTED CHANA-400GM",
                        "SAURBHI-PINTO BEANS-1 KG",
                        "SAURBHI-YELLOW SPLIT PEAS-1 KG",
                        "4 CORNER-HORSE GRAM (GAHAT)-500 GM",
                        "SAURABHI-MUNG SPLIT WITH SKIN-2KG",
                        "VIYA-RED SPLIT LENTIL/MASOOR DAL-1 KG",
                        "4 CORNER-SANO KERAU (GREEN PEAS)-500 GM",
                        "UTTAM-ROASTED CHANA DAL-200GM",
                        "VIYA-SOYA BEANS-1 KG",
                        "SPARK-ROASTED CHANA-400 GM",
                        "VIYA-MOTH BEANS-1 KG",
                        "PATTU-MOONG DAL-1KG",
                        "INDYA-ROASTED GRAM SPLITS-500GM",
                        "INDYA W CHILLI 100GM",
                        "PATTU-CHICK PEA TYSON-5 KG",
                        "PATTU-RED SPLIT LENTIL/MASOOR DAL-5 KG",
                        "PATTU-CHANNA DAL-5 KG",
                        "PATTU-RED KIDNEY BEANS LIGHT-5 KG",
                        "PATTU-RED KIDNEY BEANS LIGHT/RAJMAH-1 KG",
                        "PATTU-RED KIDNEY BEANS LIGHT/RAJMAH-2 KG",
                        "PATTU-URID/URAD WHOLE BLACK-5 KG",
                        "PATTU-CHANNA DAL-1KG",
                        "PATTU-BLACK LENTIL-1 KG",
                        "KATOOMBA-TOOR DAL-1KG",
                        "KATOOMBA-RED LENTIL-1KG",
                        "UTTAM-DALIYA-500 GM",
                        "SAURBHI-MUNG DHALL-5 KG",
                        "SAURBHI-CHICK PEAS (TYSON)-5KG",
                        "THE SPICE FACTORY-BARLEY WHOLE-200GM",
                        "SAURBHI-CHANA DHALL-2KG",
                        "HINDUSTAN-URID DHAL WHITE-5KG",
                        "SAURBHI-TOOR DHAL-5KG",
                        "PATTU-BLACK LENTIL-2 KG",
                        "PATTU-URID/URAD DAL WHITE(SPLIT)-5 KG",
                        "VIYA-BLACK EYE BEANS-1 KG",
                        "VIYA-URID/URAD WHITE SPLIT- 1 KG",
                        "PATTU-CHICK PEAS KABULI-1 KG 2",
                        "4 CORNER-BLACK BEAN DAAL- 500GM",
                        "4 CORNER-RED BEEN DAAL-500GM",
                        "SAURBHI ROASTED GRAM 850G",
                        "SAURBHI-RED SPLIT LENTILS MASOOR-1KG",
                        "SAURBHI-URID WHOLE-1KG",
                        "SAURBHI-BLACK EYE BEANS-1KG",
                        "SAURBHI-RED KIDNEY DARK-1KG",
                        "SAURBHI-ADZUKI BEANS-1KG",
                        "SAURBHI-MIXED BEANS-1KG",
                        "SAURBHI-TUVAR WHOLE-1KG",
                        "SAURBHI-RED LENTILS/MASOOR-2KG",
                        "SPARK-ROASTED CHANA-500GM",
                        "SAURBHI-MUNG DHALL YELLOW-1 KG",
                        "PATTU-CHICK PEAS LARGE 10MM- 2KG",
                        "SAURBHI-CHICK PEAS PREMIUM-5 KG",
                        "PATTU-MUNG BEANS BERKEN-5 KG",
                        "SSD-BLACK URID/URAD DAL-1 KG",
                        "SSD-RED KIDNEY BEANS DARK/RAJMAH-1 KG",
                        "PATTU-TOOR DHALL-2KG",
                        "PATTU-URID/URAD WHOLE GOTA WHITE-2KG",
                        "PATTU-BLACK EYE BEANS-5 KG",
                        "PATTU-URID SPLIT(WITH SKIN)-1KG",
                        "PATTU-URID WHOLE WHITE-5KG",
                        "PATTU-CRANBERRY BEANS-1KG",
                        "PATTU-URID SPLIT (WITH SKIN)-5 KG",
                        "VIYA-MOONG DAL-1 KG",
                        "VIYA-URID/URAD GOTA-1 KG",
                        "INDYA-MOONG DAL-2 KG",
                        "INDYA-RED SPLIT LENTIL/MASOOR DAL-1 KG",
                        "SAURBHI-BLACK LENTIL-1 KG",
                        "SPARK-ROASTED GRAM SPLIT-200 GM",
                        "PATTU-URID/URAD WHOLE BLACK-2 KG 2",
                        "PATTU-MUNG BEAN BERKEN-1 KG",
                        "PATTU-GREEN LENTIL-CANADIAN-1KG",
                        "SAURBHI-RED KIDNEY BEANS LIGHT/RAJMAH-1 KG",
                        "SAURBHI-TYSON CHICK PEAS/KALA CHANNA-1 KG",
                        "SAURBHI-BORLOTTI BEANS-1 KG",
                        "FARM KING-URID/URAD WHOLE BLACK-1 KG",
                        "KATOOMBA-MOONG BEAN BERKEN-1 KG",
                        "KATOOMBA-MOONG BEAN CELERA-1 KG",
                        "KATOOMBA-BLACK URID/URAD WHOLE-1 KG",
                        "UTTAM-ROASTED SALTY CHANA-500 GM",
                        "UTTAM-ROASTED CHANA WITH SKIN-1KG",
                        "VIYA-MOONG BEAN CELERA-1 KG",
                        "INDYA-SALTED ROASTED CHANA-800GM",
                        "KHUSHBOO-ROASTED CHANA WITH SKIN -908GM",
                        "HINDUSTAN-CHICK PEA TYSON-5KG",
                        "PARSARAM-TOOR DAL-5KG",
                        "THE SPICE FACTORY-PANJABI DAL-1KG",
                        "JAIPUR MORAIYA SEED-500GM",
                        "KT COW PEAS 1KG",
                        "INDYA-MOTH WHOLE-1KG",
                        "PATTU-URID DHALL WHITE (SPLIT)-2KG",
                        "PATTU-MOONG MASOOR MIX-2 KG",
                        "SAURBHI-MOONG MASOOR MIX-1 KG",
                        "SAURBHI-RED LENTIL GOTA-1 KG",
                        "SAURBHI-CHANNA DAL-1 KG",
                        "SAURBHI-BLUE PEAS-1 KG",
                        "SHAN-TOOR DAL-1 KG",
                        "SHAN-MOONG DAL-1 KG",
                        "SAURBHI-URID/URAD WHOLE(GOTA) WITHOUT SKIN-1 KG",
                        "MJ-WHOLE WHEAT-1 KG",
                        "SAURBHI-MOONG BEAN CELERA WHOLE-1 KG",
                        "SHAN-URID/URAD DAL-1 KG",
                        "SHAN-MOONG SPLIT WITH SKIN-1 KG",
                        "SHAN-URID/URAD SPLIT WITH SKIN -1 KG",
                        "HINDUSTAN -SOUP MIX-1KG",
                        "SAURBHI-POP CORN-1 KG",
                        "PATTU-URID SPLIT WITH SKIN-2 KG",
                        "PATTU-BLACK TURTLE BEANS-1KG",
                        "SAURBHI-SOYA BEAN-1 KG",
                        "SAURBHI-VAAL WHOLE (BEANS)-1 KG",
                        "TSF-POP CORN-500GM",
                        "INDYA-MOONG DAL-1 KG",
                        "VIYA-WHITE PEAS-1 KG",
                        "VIYA-TOOR DAL-1 KG",
                        "VIYA-CHICK PEAS ORD RIVER-1 KG",
                        "KATOOMBA-TYSON CHICK PEAS/KALA CHANNA-1 KG",
                        "SAURBHI-GREAT NORTHERN BEANS-1 KG",
                        "SAURBHI-URID/URAD SPLIT WITH SKIN-1 KG",
                        "POPCORN-KERNELS-1KG",
                        "VIYA-CHANNA DAL-1 KG",
                        "SAURBHI-CHANNA DAL-5 KG",
                        "SAURBHI-RED SPLIT LENTIL/MASOOR DAL-5 KG",
                        "VIYA-MOTH BEANS-1 KG 2",
                        "SAURBHI- TOOR DHALL- 2 KG",
                        "SAURBHI-URID DHALL WHITE SPLIT-1KG",
                        "INDIYA-WHOLE URID-1KG",
                        "TELUGU-ROASTED DALIA SPLIT-1KG",
                        "ADUKKALA-WHOLE RAGI-1KG",
                        "JK-BLACK TURTLE BEANS-1KG",
                        "HINDUSTAN-QUINOA SEED BLACK-500GM",
                        "HINDUSTAN-QUINOA SEED-500GM",
                        "HINDUSTAN-QUINOA SEEDS WHITE-500GM",
                        "JK-WHITE PEAS-1KG"
                      ];

                      const cleanList = alreadyUpdated.map(title =>
                        title.trim().toUpperCase()
                      );

                      return items.filter(item => {
                        const sheetTitle = (item.json.title || "")
                          .toString()
                          .trim()
                          .toUpperCase();

                        return !cleanList.includes(sheetTitle);
                      });
